function countNuclei(nucleusMask, GT)
% nucleusMask = nucleus mask generated by segment nuclei
% GT = ground truth image

% this function counts the nuclei found by nucleus mask and the nuclei
% inside the ground truth image and outputs them for comparison
% Miguel Manguerra and Kimiya Mousavi

    % read ground truth image
    truth = imread(GT);
    truth = im2gray(truth);
    truth = double(truth);
    
    % find black and white regions of image
    [G,L] = bwboundaries(truth,'noholes');
    [N,L] = bwboundaries(nucleusMask,'noholes');

    % output count of black and white regions of image
    fprintf("Nuclei Mask: %d\n", length(N));
    fprintf("Ground Truth: %d\n", length(G));